# Generated by Django 3.0.4 on 2020-03-17 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Auditories',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('course', models.SmallIntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('evening', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Laboratory work', 'Laboratory work'), ('Lecture', 'Lecture'), ('Practice', 'Practice'), ('Exam', 'Exam'), ('Credit', 'Credit'), ('Other', 'Other')], max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('module', models.CharField(choices=[('first_module', 'first_module'), ('second_module', 'second_module'), ('no_module', 'no_module'), ('none', 'none')], max_length=15)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Groups')),
                ('teachers', models.ManyToManyField(to='schedule.Teacher')),
            ],
        ),
    ]
