# Generated by Django 3.0.4 on 2020-03-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Auditories',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('course', models.SmallIntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('evening', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'Auditories',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.SmallIntegerField(choices=[(0, 'Laboratory work'), (1, 'Lecture')])),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('module', models.SmallIntegerField(choices=[(0, 'first_module'), (1, 'second_module'), (2, 'no_module'), (3, 'none')])),
                ('group_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Groups')),
            ],
        ),
    ]
