# Generated by Django 3.0.4 on 2020-03-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Auditories',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('course', models.SmallIntegerField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('is_evening', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'Group',
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('old_lesson', models.TextField()),
                ('new_lesson', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_of_week', models.IntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')])),
                ('number', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('week', models.IntegerField(choices=[(1, 'even'), (2, 'odd'), (3, 'both')])),
                ('classrooms', models.ManyToManyField(to='schedule.Classroom')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Groups')),
                ('teachers', models.ManyToManyField(to='schedule.Teacher')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LessonType')),
            ],
        ),
    ]
