# Generated by Django 3.0.4 on 2020-03-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'group', 'verbose_name_plural': 'Group'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.CharField(choices=[('first_module', 'first_module'), ('second_module', 'second_module'), ('no_module', 'no_module'), ('none', 'none')], max_length=15),
        ),
    ]
