# Generated by Django 3.0.4 on 2020-06-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_session',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
