# Generated by Django 3.0.4 on 2020-03-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200317_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='classrooms',
            field=models.ManyToManyField(blank=True, null=True, to='schedule.Auditory'),
        ),
    ]
