# Generated by Django 3.0.4 on 2020-03-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200315_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('Laboratory work', 'Laboratory work'), ('Lecture', 'Lecture')], max_length=20),
        ),
    ]
