# Generated by Django 3.0.4 on 2020-05-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200327_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='targets',
            field=models.TextField(default='popa'),
            preserve_default=False,
        ),
    ]
