# Generated by Django 3.0.4 on 2020-03-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_lesson_classrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='monday', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_idx',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
