# Generated by Django 3.0.4 on 2020-06-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_lesson_is_session'),
        ('schedule', '0004_notification_targets'),
    ]

    operations = [
    ]
